# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1712, 934)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 150, 1031, 681))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(1160, 850, 171, 51))
        self.start.setObjectName("start")
        self.Trigger = QtWidgets.QPushButton(self.centralwidget)
        self.Trigger.setGeometry(QtCore.QRect(1440, 850, 171, 51))
        self.Trigger.setObjectName("Trigger")
        self.Model = QtWidgets.QComboBox(self.centralwidget)
        self.Model.setGeometry(QtCore.QRect(1440, 180, 181, 31))
        self.Model.setObjectName("Model")
        self.Model.addItem("")
        self.Model.addItem("")
        self.Model.addItem("")
        self.Model.addItem("")
        self.Pos = QtWidgets.QComboBox(self.centralwidget)
        self.Pos.setGeometry(QtCore.QRect(1440, 270, 181, 31))
        self.Pos.setObjectName("Pos")
        self.perc_ent = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.perc_ent.setGeometry(QtCore.QRect(1440, 360, 181, 31))
        self.perc_ent.setObjectName("perc_ent")
        self.Model_number = QtWidgets.QLabel(self.centralwidget)
        self.Model_number.setGeometry(QtCore.QRect(1120, 180, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.Model_number.setFont(font)
        self.Model_number.setObjectName("Model_number")
        self.Position = QtWidgets.QLabel(self.centralwidget)
        self.Position.setGeometry(QtCore.QRect(1120, 270, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.Position.setFont(font)
        self.Position.setObjectName("Position")
        self.Percentage = QtWidgets.QLabel(self.centralwidget)
        self.Percentage.setGeometry(QtCore.QRect(1120, 360, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.Percentage.setFont(font)
        self.Percentage.setObjectName("Percentage")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1100, 410, 601, 421))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.Trigger.setText(_translate("MainWindow", "Trigger"))
        self.Model.setItemText(0, _translate("MainWindow", "RR20"))
        self.Model.setItemText(1, _translate("MainWindow", "RR28"))
        self.Model.setItemText(2, _translate("MainWindow", "RT34"))
        self.Model.setItemText(3, _translate("MainWindow", "RT37"))
        self.Model_number.setText(_translate("MainWindow", "Model Number"))
        self.Position.setText(_translate("MainWindow", "Camera Position"))
        self.Percentage.setText(_translate("MainWindow", "Percentage"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
